"""empty message

Revision ID: 911462184f56
Revises: 5274e6d52e66
Create Date: 2022-08-27 17:52:26.586129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911462184f56'
down_revision = '5274e6d52e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basket', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('basket', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'basket', 'product', ['product_id'], ['id'])
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.alter_column('basket', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('basket', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
