"""empty message

Revision ID: a0a409102c79
Revises: f541509fac50
Create Date: 2022-09-13 15:17:17.543850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a409102c79'
down_revision = 'f541509fac50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('basket', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('basket', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('basket', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('basket', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('basket', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('basket', 'id')
    # ### end Alembic commands ###
