"""empty message

Revision ID: f541509fac50
Revises: 911462184f56
Create Date: 2022-08-27 18:38:23.554550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f541509fac50'
down_revision = '911462184f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'basket', 'product', ['product_id'], ['id'])
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    op.drop_constraint(None, 'basket', type_='foreignkey')
    # ### end Alembic commands ###
